service: layer-moment

provider:
  name: aws
  runtime: nodejs10.x
  stage: 'dev'
  region: 'us-east-2'
  deploymentBucket:
    name: cf-templates-5rrcz2248gen-${self:provider.region}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: any
          private: false
